### ISSUE TITLE
为什么修改了config.ini文件打开的时候还是没有跳转到设置的页面啊

### ISSUE THREAD

**Issue by WSAHi** [huaisha1224/QualityCenterBrowser#2]
配置信息如下:
[info]
url = http://10.24.1.111:8080/qcbin/start_a.jsp

[version]
version = 1.5	
Build = 20180321

[about]
Author:Sam Huang
Email:sam.hxq@gmail.com

**Comment by huaisha1224** [comment]
url = 10.24.1.111:8080/qcbin/start_a.jsp
这样的
